### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by schneidexe** [schneidexe/tpl#4]
```
15:23:57 + tpl -t docker/etc/sensu/local.checks.d/article-shop-quantity-updater.checks.json.tpl
15:23:57 panic: runtime error: invalid memory address or nil pointer dereference
15:23:57 [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x51fd59]
15:23:57 
15:23:57 goroutine 1 [running]:
15:23:57 main.inputToObject(0xc42000a136, 0x4, 0xc42007a16e, 0x1, 0xc4200a0260, 0x2, 0x2)
15:23:57 	/Users/thomassc/work/go/src/github.com/schneidexe/tpl/tpl.go:57 +0x719
15:23:57 main.main()
15:23:57 	/Users/thomassc/work/go/src/github.com/schneidexe/tpl/tpl.go:100 +0x23f
```

**Comment by schneidexe** [comment]
Issue happens when setting an env var with the value ```null```.
